name: GKE of data-forge

on:
  workflow_dispatch:
    inputs:
      base:
        required: true
        type: string
      head:
        required: true
        type: string
      version:
        required: true
        type: string

jobs:
  deploy-to-gke:
    name: Deploy data-forge to GKE
    runs-on: ubuntu-latest
    environment: production
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GIT_TOKEN }}

      # Set up the Node.js environment
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      # Alternative option - authentication via credentials json
      - name: Authenticate to Google Cloud
        id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      # Setup gcloud CLI
      - name: Set up GCloud
        uses: google-github-actions/setup-gcloud@v1

      # Get the GKE credentials
      - name: Get the GKE credentials
        uses: google-github-actions/get-gke-credentials@v1
        with:
          cluster_name: appcraft-cluster
          location: asia-east1-a

      # Build Docker image
      - name: Build Docker Image
        run: |
          npm ci
          npx nx build data-forge --configuration=production
          docker build \
            -f ./apps/data-forge/Dockerfile . \
            -t gcr.io/${{ vars.GCP_PROJECT }}/data-forge:v${{ inputs.version }}

      # Push the Docker Image to GCR
      - name: Push the Docker Image to GCR
        run: |
          gcloud --quiet auth configure-docker
          docker push gcr.io/${{ vars.GCP_PROJECT }}/data-forge:v${{ inputs.version }}

      # Connect GKE
      - name: Connect GKE
        uses: google-github-actions/get-gke-credentials@v1
        with:
          cluster_name: appcraft-cluster
          location: asia-east1-a

      - name: Update Image
        run: |
          kubectl set image \
            deployment/appcraft \
            data-forge-sha256-1=gcr.io/${{ vars.GCP_PROJECT }}/data-forge:v${{ inputs.version }} \
            -n dev
