name: NPM Publish of mui

on:
  workflow_dispatch:
    inputs:
      base:
        required: true
        type: string
      head:
        required: true
        type: string
      version:
        required: true
        type: string

jobs:
  publish-to-npm:
    name: Publish types to NPM
    runs-on: ubuntu-latest
    environment: production
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GIT_TOKEN }}

      # Set up the Node.js environment
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Build
        run: |
          npm ci
          npx nx build mui
          cd ./dist/libs/mui
          npm version ${{ inputs.version }} --no-git-tag-version

      - uses: JS-DevTools/npm-publish@v1
        with:
          package: ./dist/libs/types/package.json
          access: public
          token: ${{ secrets.NPM_TOKEN }}
